# Frappe Bench Dockerfile

FROM ubuntu:18.04
LABEL author=frappé

  RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends locales \
    && sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen \
    && dpkg-reconfigure --frontend=noninteractive locales \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Set locale en_us.UTF-8 for mariadb and general locale data
ENV PYTHONIOENCODING=utf-8
ENV LANGUAGE=en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8

# Install all neccesary packages
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-suggests --no-install-recommends \
  build-essential cron curl git libffi-dev liblcms2-dev libldap2-dev libmariadbclient-dev libsasl2-dev libssl1.0-dev libtiff5-dev \
  libwebp-dev mariadb-client iputils-ping python python-pip python-setuptools python-tk redis-tools rlwrap \
  software-properties-common sudo tk8.6-dev vim xfonts-75dpi xfonts-base wget wkhtmltopdf fonts-cantarell supervisor \
  && apt-get clean && rm -rf /var/lib/apt/lists/* \
  && curl https://deb.nodesource.com/node_10.x/pool/main/n/nodejs/nodejs_10.10.0-1nodesource1_amd64.deb > node.deb \
  && dpkg -i node.deb \
  && rm node.deb \
  && npm install -g yarn

# Install wkhtmltox correctly
RUN wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.bionic_amd64.deb
RUN dpkg -i wkhtmltox_0.12.5-1.bionic_amd64.deb && rm wkhtmltox_0.12.5-1.bionic_amd64.deb

# Add frappe user and setup sudo
RUN groupadd -g 500 frappe \
  && useradd -ms /bin/bash -u 500 -g 500 -G sudo frappe \
  && printf '# Sudo rules for frappe\nfrappe ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/frappe \
  && chown -R 500:500 /home/frappe

# Install bench
RUN pip install -e git+https://github.com/frappe/bench.git#egg=bench --no-cache

USER frappe

# Add some bench files
#COPY --chown=frappe:frappe ./frappe-bench /home/frappe/frappe-bench



#RUN bench init frappe-bench --ignore-exist --skip-redis-config-generation --python python2  --frappe-branch version-11
#RUN rm -rf /home/frappe/frappe-bench/sites/common_site_config.json 
#RUN ln -s /home/frappe/frappe-link/common_site_config.json /home/frappe/frappe-bench/sites/common_site_config.json 
#RUN rm -rf /home/frappe/frappe-bench/Procfile 
#RUN ln -s /home/frappe/frappe-link/Procfile /home/frappe/frappe-bench/Procfile 
# sudo ln -s /home/frappe/frappe-bench/config/supervisor.conf /etc/supervisor/conf.d/frappe-bench.conf
#cp -rf /home/frappe/frappe-link/python_lib/* /home/frappe/frappe-bench/env/lib/python2.7/site-packages/


#On Docker File Start Ningx/Supervisor
#sudo /etc/init.d/nginx start
#sudo /etc/init.d/supervisor start


#cp -rf /home/frappe/frappe-bench/sites/ /home/frappe/frappe-link/frappe-bench/

WORKDIR /home/frappe/

EXPOSE 8000 9000 6787
